#include "main.h"

char **envp_vars() 
{
	char **envp = NULL;
	int num_vars = 0, i, len = 0;
	char *env_vars[] = {"LESS_TERMCAP_se", "HISTFILESIZE", "LANGUAGE", "USER",
	"LESS_TERMCAP_ue", "LC_TIME", "STARSHIP_SHELL", "XDG_SESSION_TYPE",
	"SHLVL", "HOME", "OLDPWD", "DESKTOP_SESSION",
	"GNOME_SHELL_SESSION_MODE","GTK_MODULES", "LESS_TERMCAP_so",
	"LC_MONETARY", "DBUS_STARTER_BUS_TYPE", "SYSTEMD_EXEC_PID",
	"VISUAL", "DBUS_SESSION_BUS_ADDRESS","COLORTERM", "IM_CONFIG_CHECK_ENV",
	 "DEBUGINFOD_URLS","IM_CONFIG_PHASE",
	"WAYLAND_DISPLAY", "LOGNAME", "LESS_TERMCAP_us",
	"XDG_SESSION_CLASS", "USERNAME", "TERM", "GNOME_DESKTOP_SESSION_ID",
	"AUTOJUMP_ERROR_PATH", "HISTCONTROL", "PATH", "SESSION_MANAGER",
	"PAPERSIZE", "XDG_MENU_PREFIX", "LC_ADDRESS", "GNOME_TERMINAL_SCREEN",
	"GNOME_SETUP_DISPLAY", "XDG_RUNTIME_DIR", "DISPLAY", "HISTSIZE","LANG",
        "XDG_CURRENT_DESKTOP", "LC_TELEPHONE", "XMODIFIERS",
	"XDG_SESSION_DESKTOP", "XAUTHORITY", "LS_COLORS",
	"GNOME_TERMINAL_SERVICE", "SSH_AGENT_LAUNCHER", "SSH_AUTH_SOCK",
	"SHELL", "LC_NAME", "QT_ACCESSIBILITY", "GDMSESSION",
	"LESS_TERMCAP_mb", "LC_MEASUREMENT", "LC_IDENTIFICATION",
	"LESS_TERMCAP_md", "QT_IM_MODULE", "PWD", "CLICOLOR", "LESS_TERMCAP_me",
        "XDG_CONFIG_DIRS", "DBUS_STARTER_ADDRESS", "XDG_DATA_DIRS",
	"STARSHIP_SESSION_KEY","AUTOJUMP_SOURCED","LC_NUMERIC", "LC_PAPER",
	"VTE_VERSION", "EDITOR",
	};
	
	num_vars = sizeof(env_vars) / sizeof(env_vars[0]);
	envp = (char **)malloc((num_vars + 1) * sizeof(char *));
	if (envp == NULL)
		return NULL;

	for (i = 0; i < num_vars; i++)
	{
		len += strlen(env_vars[i]);
		envp[i] = strdup(env_vars[i]);
	}
	envp[i] = NULL;
	return (envp);
}
